<a href="https://colab.research.google.com/github/3b232106/2026_DL_hws/blob/main/hw2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 作業2 - 四資四乙 3B232106 陳威廷

In [1]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def relu(x):
    return np.maximum(0, x)

# 適用於批次矩陣計算的 Softmax 函數
def softmax(x):
    x = x - np.max(x, axis=-1, keepdims=True)
    return np.exp(x) / np.sum(np.exp(x), axis=-1, keepdims=True)

# 適用於批次矩陣計算的 Cross Entropy Error (計算整批平均誤差)
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)

    batch_size = y.shape[0]
    return -np.sum(t * np.log(y + 1e-7)) / batch_size

多層神經網路小批次學習, 設定批次大小為 5

In [2]:
batch_size = 5

輸入層 : 自行產生 5 筆訓練資料（每筆 6 個特徵值）

In [3]:
# 五筆輸入資料 X，每個 x 有 6 個特徵值
X = np.array([
    [1.0, 0.5, 0.2, 0.8, 0.3, 0.6],
    [0.8, 0.1, 0.9, 0.4, 0.5, 0.2],
    [0.3, 0.7, 0.1, 0.6, 0.9, 0.4],
    [0.5, 0.5, 0.5, 0.2, 0.1, 0.8],
    [0.2, 0.9, 0.4, 0.3, 0.7, 0.1]
])

# 五筆對應的真實標籤 Y (3 個類別)
Y = np.array([
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
    [1, 0, 0]
])

print("X 陣列形狀 Shape:", X.shape)
print("X 內容:\n", X)
print("\nY 陣列形狀 Shape:", Y.shape)
print("Y 內容:\n", Y)

X 陣列形狀 Shape: (5, 6)
X 內容:
 [[1.  0.5 0.2 0.8 0.3 0.6]
 [0.8 0.1 0.9 0.4 0.5 0.2]
 [0.3 0.7 0.1 0.6 0.9 0.4]
 [0.5 0.5 0.5 0.2 0.1 0.8]
 [0.2 0.9 0.4 0.3 0.7 0.1]]

Y 陣列形狀 Shape: (5, 3)
Y 內容:
 [[0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]]


第一層

In [4]:
# 權重 W1 與偏值 b1 (沿用作業 1)
W1 = np.array([
    [0.1, 0.2, 0.3, 0.4, 0.5],
    [0.2, 0.1, 0.4, 0.3, 0.2],
    [0.1, 0.3, 0.2, 0.5, 0.1],
    [0.4, 0.2, 0.1, 0.3, 0.4],
    [0.3, 0.5, 0.2, 0.1, 0.3],
    [0.2, 0.4, 0.3, 0.2, 0.1]
])
b1 = np.array([0.1, 0.2, 0.1, 0.3, 0.2])

print("X Shape:", X.shape)
print("W1 Shape:", W1.shape)
print("b1 Shape:", b1.shape)

Z1 = np.dot(X, W1) + b1
print("\nZ1 Shape:", Z1.shape)
print("Z1 內容:\n", Z1)

H1 = relu(Z1)
print("\nH1 (ReLU) Shape:", H1.shape)
print("H1 內容:\n", H1)

X Shape: (5, 6)
W1 Shape: (6, 5)
b1 Shape: (5,)

Z1 Shape: (5, 5)
Z1 內容:
 [[0.85 1.06 0.96 1.34 1.29]
 [0.64 1.05 0.76 1.31 1.04]
 [0.87 1.09 0.85 1.03 1.05]
 [0.57 0.91 0.83 1.13 0.79]
 [0.69 0.9  0.8  1.03 0.86]]

H1 (ReLU) Shape: (5, 5)
H1 內容:
 [[0.85 1.06 0.96 1.34 1.29]
 [0.64 1.05 0.76 1.31 1.04]
 [0.87 1.09 0.85 1.03 1.05]
 [0.57 0.91 0.83 1.13 0.79]
 [0.69 0.9  0.8  1.03 0.86]]


第二層

In [5]:
# 權重 W2 與偏值 b2
W2 = np.array([
    [0.1, 0.3, 0.2, 0.4],
    [0.2, 0.1, 0.5, 0.3],
    [0.3, 0.4, 0.1, 0.2],
    [0.4, 0.2, 0.3, 0.1],
    [0.1, 0.5, 0.2, 0.3]
])
b2 = np.array([0.1, 0.2, 0.1, 0.2])

print("H1 Shape:", H1.shape)
print("W2 Shape:", W2.shape)
print("b2 Shape:", b2.shape)

Z2 = np.dot(H1, W2) + b2
print("\nZ2 Shape:", Z2.shape)
print("Z2 內容:\n", Z2)

H2 = relu(Z2)
print("\nH2 (ReLU) Shape:", H2.shape)
print("H2 內容:\n", H2)

H1 Shape: (5, 5)
W2 Shape: (5, 4)
b2 Shape: (4,)

Z2 Shape: (5, 4)
Z2 內容:
 [[1.35  1.858 1.556 1.571]
 [1.23  1.583 1.43  1.366]
 [1.177 1.641 1.423 1.463]
 [1.119 1.415 1.249 1.217]
 [1.087 1.453 1.249 1.267]]

H2 (ReLU) Shape: (5, 4)
H2 內容:
 [[1.35  1.858 1.556 1.571]
 [1.23  1.583 1.43  1.366]
 [1.177 1.641 1.423 1.463]
 [1.119 1.415 1.249 1.217]
 [1.087 1.453 1.249 1.267]]


第三層

In [6]:
# 權重 W3 與偏值 b3
W3 = np.array([
    [0.2, 0.1, 0.3, 0.4],
    [0.1, 0.4, 0.2, 0.3],
    [0.3, 0.2, 0.5, 0.1],
    [0.4, 0.3, 0.1, 0.2]
])
b3 = np.array([0.1, 0.1, 0.2, 0.1])

print("H2 Shape:", H2.shape)
print("W3 Shape:", W3.shape)
print("b3 Shape:", b3.shape)

Z3 = np.dot(H2, W3) + b3
print("\nZ3 Shape:", Z3.shape)
print("Z3 內容:\n", Z3)

H3 = sigmoid(Z3)
print("\nH3 (Sigmoid) Shape:", H3.shape)
print("H3 內容:\n", H3)

H2 Shape: (5, 4)
W3 Shape: (4, 4)
b3 Shape: (4,)

Z3 Shape: (5, 4)
Z3 內容:
 [[1.651  1.7607 1.9117 1.6672]
 [1.4797 1.552  1.7372 1.4831]
 [1.5116 1.5976 1.7391 1.498 ]
 [1.3268 1.3928 1.5649 1.3404]
 [1.3442 1.4198 1.5679 1.349 ]]

H3 (Sigmoid) Shape: (5, 4)
H3 內容:
 [[0.83902616 0.85329731 0.87121001 0.84120215]
 [0.81452726 0.82520241 0.85033106 0.81504036]
 [0.81929821 0.83168268 0.85057271 0.81727599]
 [0.79031082 0.80103887 0.82705535 0.79255571]
 [0.79317978 0.80530706 0.82748403 0.79396609]]


第四層

In [7]:
# 權重 W4 與偏值 b4
W4 = np.array([
    [0.1, 0.3, 0.5],
    [0.2, 0.4, 0.1],
    [0.3, 0.1, 0.4],
    [0.4, 0.2, 0.3]
])
b4 = np.array([0.1, 0.2, 0.1])

print("H3 Shape:", H3.shape)
print("W4 Shape:", W4.shape)
print("b4 Shape:", b4.shape)

Z4 = np.dot(H3, W4) + b4
print("\nZ4 Shape:", Z4.shape)
print("Z4 內容:\n", Z4)

y_hat = softmax(Z4)
print("\ny_hat (Softmax) Shape:", y_hat.shape)
print("y_hat 內容:\n", y_hat)

H3 Shape: (5, 4)
W4 Shape: (4, 3)
b4 Shape: (3,)

Z4 Shape: (5, 3)
Z4 內容:
 [[0.95240594 1.0483882  1.20568746]
 [0.92760867 1.02248032 1.17442841]
 [0.93034857 1.02697501 1.17822925]
 [0.90437775 0.99872547 1.14384815]
 [0.90621104 1.00161838 1.14630404]]

y_hat (Softmax) Shape: (5, 3)
y_hat 內容:
 [[0.29507356 0.32479914 0.3801273 ]
 [0.29590473 0.32535249 0.37874277]
 [0.29561696 0.32560695 0.37877609]
 [0.29677836 0.32614215 0.37707949]
 [0.29660615 0.32629847 0.37709538]]


Cross Entropy Error（計算整批 5 筆的平均誤差）

In [8]:
# 使用修正後的 cross_entropy_error 函數計算整批五筆資料的平均誤差
loss = cross_entropy_error(y_hat, Y)

print("整批 (五筆) y_hat 與 Y 的 Cross Entropy Error 平均值:", loss)

整批 (五筆) y_hat 與 Y 的 Cross Entropy Error 平均值: 1.0995357948407678
